using System;
using iTextSharp.GE.text.pdf;

namespace iTextSharp.GE.text.pdf.richmedia {

    /**
     * The RichMediaPresentation dictionary contains information about how the
     * annotation and user interface elements are to be visually laid out and
     * drawn.
     * See ExtensionLevel 3 p82
     * @since   5.0.0
     */
    public class RichMediaPresentation : PdfDictionary {
        
        /**
         * Creates a RichMediaPresentation dictionary.
         */
        public RichMediaPresentation() : base(PdfName.RICHMEDIAPRESENTATION) {
        }
        
        /**
         * Sets the style for the presentation;
         * can be embedded or windowed.
         * @param   style PdfName.EMBEDDED or PdfName.WINDOWED
         */
        virtual public PdfName Style {
            set {
                Put(PdfName.STYLE, value);
            }
        }
        
        /**
         * A RichMediaWindow Dictionary that describes the size and
         * position of the floating user interface window when the
         * value for Style is set to Windowed.
         * @param   window  a RichMediaWindow object
         */
        virtual public RichMediaWindow Window {
            set {
                Put(PdfName.WINDOW, value);
            }
        }
        
        /**
         * Set a flag that indicates whether the page content is displayed
         * through the transparent areas of the rich media content (where
         * the alpha value is less than 1.0). If true, the rich media artwork
         * is composited over the page content using an alpha channel. If false,
         * the rich media artwork is drawn over an opaque background prior to
         * composition over the page content.
         * @param   transparent a bool
         */
        virtual public PdfBoolean Transparent {
            set {
                Put(PdfName.TRANSPARENT, value);
            }
        }
        
        /**
         * Sets a flag that indicates the default behavior of the navigation pane
         * user interface element. If true, the navigation pane is visible when
         * the content is initially activated. If false, the navigation pane is
         * not displayed by default.
         * @param   navigationPane  a bool
         */
        virtual public PdfBoolean NavigationPane {
            set {
                Put(PdfName.NAVIGATIONPANE, value);
            }
        }

        /**
         * Sets a flag that indicates the default behavior of an interactive
         * toolbar associated with this annotation. If true, a toolbar is
         * displayed when the annotation is activated and given focus. If false,
         * a toolbar is not displayed by default.
         * @param   toolbar a bool
         */
        virtual public PdfBoolean Toolbar {
            set {
                Put(PdfName.TOOLBAR, value);
            }
        }

        /**
         * Sets a flag that indicates whether a context click on the rich media
         * annotation is passed to the media player run time or is handled by
         * the conforming reader. If false, the conforming reader handles the
         * context click. If true, the conforming reader's context menu is not
         * visible, and the user sees the context menu and any custom items
         * generated by the media player run time.
         * @param   passContextClick    a bool
         */
        virtual public PdfBoolean PassContextClick {
            set {
                Put(PdfName.PASSCONTEXTCLICK, value);
            }
        }
    }
}
